- id: ast-grep
  name: ast-grep
  description: "A CLI tool for code structural search, lint and rewriting. Written in Rust"
  entry: ast-grep scan --color=never
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: false
  types: [text]